apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: edb-postgres
  namespace: lab-workloads
  labels:
    app.kubernetes.io/name: edb-postgres-workload
    app.kubernetes.io/part-of: kafka-edb-lab
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2
  bootstrap:
    initdb:
      database: app
      owner: app
  affinity:
    nodeSelector:
      kubernetes.io/hostname: minikube-m02
  resources:
    requests:
      cpu: "1200m"
      memory: "1024Mi"
    limits:
      cpu: "2000m"
      memory: "2048Mi"
  storage:
    size: 5Gi
  postgresql:
    parameters:
      shared_buffers: "512MB"
      max_connections: "200"
      work_mem: "32MB"
      checkpoint_completion_target: "0.9"
      synchronous_commit: "on"
