apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker-pool
  namespace: lab-workloads
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  roles:
    - controller
    - broker
  replicas: 1
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: true
  resources:
    requests:
      cpu: "1200m"
      memory: "1536Mi"
    limits:
      cpu: "2000m"
      memory: "2560Mi"
  jvmOptions:
    -Xms: "1024m"
    -Xmx: "1024m"
  template:
    pod:
      metadata:
        labels:
          app.kubernetes.io/name: kafka-workload
          app.kubernetes.io/part-of: kafka-edb-lab
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - minikube-m02
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: lab-workloads
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.7.0
    metadataVersion: 3.7-IV4
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      log.flush.interval.messages: 1000
      log.flush.interval.ms: 1000
  entityOperator:
    topicOperator: {}
    userOperator: {}
